### ISSUE TITLE
Fix uvloop requirement

### ISSUE THREAD

**Issue by davfsa** [parafoxia/hikari-intro#5]
For uvloop requirements, it should be:
```diff 
- uvloop>=0.16; sys_platform != 'nt'
+ uvloop>=0.16; sys_platform != 'win32'
```

After @FasterSpeeding pointed it out to me today. I unfortunately cant open a pull request to fix it atm, but I am so sorry for the confusion and any projects that built over this one

**Comment by parafoxia** [comment]
No worries. I'll fix it when I get back on my computer (shouldn't be any more than an hour).
